BookHub/WebApp/Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using App.DAL.EF;
using App.Domain.Entities;

namespace WebApp.Controllers
{
    public class AuthorsController : Controller
    {
        private readonly AppDbContext _context;

        public AuthorsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Authors
        public async Task<IActionResult> Index()
        {
            return View(await _context.Authors.ToListAsync());
        }

        // GET: Authors/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _context.Authors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (author == null)
            {
                return NotFound();
            }

            var authorsBooks = await _context.BooksAuthors.Include(ba => ba.Book).Where(ba => ba.AuthorId == author.Id).Select(ba => ba.Book).ToListAsync();
            if (authorsBooks.Any())
            {
                // Получаем все BookId из booksQuery
                var bookIds = authorsBooks.Select(b => b!.Id);
                // Оставляем в ratingsQuery только те записи, где BookId присутствует в bookIds
                var ratings = await _context.Ratings.Where(r => bookIds.Contains(r.BookId)).ToListAsync();
                ViewData["Ratings"] = ratings;
            }
            ViewData["AuthorsBooks"] = authorsBooks;
            return View(author);
        }

        // GET: Authors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Authors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Age,Biography,Id")] Author author)
        {
            if (ModelState.IsValid)
            {
                author.Id = Guid.NewGuid();
                _context.Add(author);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        // GET: Authors/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _context.Authors.FindAsync(id);
            if (author == null)
            {
                return NotFound();
            }
            return View(author);
        }

        // POST: Authors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Name,Age,Biography,Id")] Author author)
        {
            if (id != author.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(author);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AuthorExists(author.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        // GET: Authors/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _context.Authors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }

        // POST: Authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var author = await _context.Authors.FindAsync(id);
            if (author != null)
            {
                _context.Authors.Remove(author);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AuthorExists(Guid id)
        {
            return _context.Authors.Any(e => e.Id == id);
        }
    }
}

BookHub/WebApp/Controllers/DiscussionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using App.Contracts.DAL;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using App.DAL.EF;
using App.Domain.Entities;

namespace WebApp.Controllers
{
    public class DiscussionsController : Controller
    {
        private readonly AppDbContext _context;

        public DiscussionsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Discussions
        public async Task<IActionResult> Index()
        {
            var appDbContext = _context.Discussions.Include(d => d.AppUser).Include(d => d.Author).Include(d => d.Book).Include(d => d.Genre);
            return View(await appDbContext.ToListAsync());
        }

        // GET: Discussions/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var discussion = await _context.Discussions
                .Include(d => d.AppUser)
                .Include(d => d.Author)
                .Include(d => d.Book)
                .Include(d => d.Genre)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (discussion == null)
            {
                return NotFound();
            }

            // Load the associated topics for the discussion
            /*var topics = await _uow.Topics.GetAllByDiscussionIdAsync(discussion.Id);*/
             var topics = _context.Topics
                 .Where(t => t.DiscussionId == discussion.Id);

            // Load messages related to the topics within the discussion
            /*var messages2 = await _uow.Messages.GetAllByTopicsAsync(topics);*/
             var messages = await _context.Messages
                 .Where(m => topics.Select(t => t.Id).Contains(m.TopicId))
                 .ToListAsync();

            // Pass the messages to the view
            ViewData["Messages"] = messages.ToList();

            // Pass the topics to the view
            ViewData["Topics"] = await topics.ToListAsync();
            return View(discussion);
        }

        // GET: Discussions/Create
        public IActionResult Create()
        {
            ViewData["AppUserId"] = new SelectList(_context.Users, "Id", "Id");
            ViewData["AuthorId"] = new SelectList(_context.Authors, "Id", "Name");
            ViewData["BookId"] = new SelectList(_context.Books, "Id", "Tittle");
            ViewData["GenreId"] = new SelectList(_context.Genres, "Id", "Name");
            return View();
        }

        // POST: Discussions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BookId,GenreId,AuthorId,AppUserId,Tittle,Description,Id")] Discussion discussion, IFormFile imageData)
        {
            if (ModelState.IsValid)
            {
                
                if (imageData != null && imageData.Length > 0)
                {
                    using (var memoryStream = new MemoryStream())
                    {
                        await imageData.CopyToAsync(memoryStream);
                        discussion.imageData = memoryStream.ToArray();
                    }
                }
                
                discussion.Id = Guid.NewGuid();
                discussion.CreationTime = DateTime.UtcNow;
                _context.Add(discussion);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AppUserId"] = new SelectList(_context.Users, "Id", "Id", discussion.AppUserId);
            ViewData["AuthorId"] = new SelectList(_context.Authors, "Id", "Name", discussion.AuthorId);
            ViewData["BookId"] = new SelectList(_context.Books, "Id", "Tittle", discussion.BookId);
            ViewData["GenreId"] = new SelectList(_context.Genres, "Id", "Name", discussion.GenreId);
            return View(discussion);
        }

        // GET: Discussions/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var discussion = await _context.Discussions.FindAsync(id);
            if (discussion == null)
            {
                return NotFound();
            }
            ViewData["AppUserId"] = new SelectList(_context.Users, "Id", "Id", discussion.AppUserId);
            ViewData["AuthorId"] = new SelectList(_context.Authors, "Id", "Name", discussion.AuthorId);
            ViewData["BookId"] = new SelectList(_context.Books, "Id", "Tittle", discussion.BookId);
            ViewData["GenreId"] = new SelectList(_context.Genres, "Id", "Name", discussion.GenreId);
            return View(discussion);
        }

        // POST: Discussions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("BookId,GenreId,AuthorId,AppUserId,Tittle,Description,Id")] Discussion discussion, IFormFile imageData)
        {
            if (id != discussion.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                
                if (imageData != null && imageData.Length > 0)
                {
                    using (var memoryStream = new MemoryStream())
                    {
                        await imageData.CopyToAsync(memoryStream);
                        discussion.imageData = memoryStream.ToArray();
                    }
                }
                
                try
                {
                    _context.Update(discussion);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DiscussionExists(discussion.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AppUserId"] = new SelectList(_context.Users, "Id", "Id", discussion.AppUserId);
            ViewData["AuthorId"] = new SelectList(_context.Authors, "Id", "Name", discussion.AuthorId);
            ViewData["BookId"] = new SelectList(_context.Books, "Id", "Tittle", discussion.BookId);
            ViewData["GenreId"] = new SelectList(_context.Genres, "Id", "Name", discussion.GenreId);
            return View(discussion);
        }

        // GET: Discussions/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var discussion = await _context.Discussions
                .Include(d => d.AppUser)
                .Include(d => d.Author)
                .Include(d => d.Book)
                .Include(d => d.Genre)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (discussion == null)
            {
                return NotFound();
            }

            return View(discussion);
        }

        // POST: Discussions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var discussion = await _context.Discussions.FindAsync(id);
            if (discussion != null)
            {
                _context.Discussions.Remove(discussion);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DiscussionExists(Guid id)
        {
            return _context.Discussions.Any(e => e.Id == id);
        }
    }
}

BookHub/WebApp/Views/Discussions/Create.cshtml
@using System.Security.Claims
@model App.Domain.Entities.Discussion

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Discussion</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BookId" class="control-label">Book</label>
                <select asp-for="BookId" class="form-control" asp-items="ViewBag.BookId">
                    <option value="">Select Book</option>
                </select>
            </div>
            
            <div class="form-group">
                <label asp-for="GenreId" class="control-label">Genre</label>
                <select asp-for="GenreId" class="form-control" asp-items="ViewBag.GenreId">
                    <option value="">Select Genre</option>
                </select>
            </div>
            
            <div class="form-group">
                <label asp-for="AuthorId" class="control-label">Author</label>
                <select asp-for="AuthorId" class="form-control" asp-items="ViewBag.AuthorId">
                    <option value="">Select Author</option>
                </select>
            </div>
            
            @* Select current user *@
            <input asp-for="AppUserId" class="form-control" type="hidden" value="@User.FindFirstValue(ClaimTypes.NameIdentifier)"/>
            
            <div class="form-group">
                <label asp-for="Tittle" class="control-label"></label>
                <input asp-for="Tittle" class="form-control" />
                <span asp-validation-for="Tittle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="imageData" class="control-label">Image</label>
                <input asp-for="imageData" class="form-control" type="file" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BookHub/WebApp/Views/Discussions/Delete.cshtml
@model App.Domain.Entities.Discussion

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Discussion</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Book)
        </dt>
        <dd class = "col-sm-10">
            @if (Model.Book != null)
            {
                @Html.DisplayFor(model => model.Book!.Tittle)
            }
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @if (Model.Genre != null)
            {
                @Html.DisplayFor(model => model.Genre!.Name)
            }
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @if (Model.Author != null)
            {
                @Html.DisplayFor(model => model.Author!.Name)
            }
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AppUser)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AppUser!.UserName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tittle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tittle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BookHub/WebApp/Views/Discussions/Details.cshtml
@using App.Domain.Address_Tables
@using App.Domain.Entities
@using System.Security.Claims
@using Microsoft.IdentityModel.Tokens
@using Message = NuGet.Protocol.Plugins.Message
@model App.Domain.Entities.Discussion

@{
    ViewData["Title"] = "Details";
}

<h1>@Html.DisplayFor(model => model.Tittle)</h1>

<div>
    <h4>Discussion</h4>
    <hr />
    <dl class="row">
        @if (!Model.imageData.IsNullOrEmpty())
        {
            <dt>Picture</dt>
            <dd>
                <img src="data:image;base64,@Convert.ToBase64String(Model.imageData)" width="180px" height="270px" alt="Picture not found!"/>
            </dd>
        }
        @if (User.Identity!.IsAuthenticated && User.Identity!.Name!.Equals(Model.AppUser!.UserName))
        {
            <span><a asp-area="" asp-controller="Discussions" asp-action="Edit" asp-route-id="@Model.Id">Edit</a></span>
        }
        @if (Model.Book != null)
        {
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Book)
            </dt>
            <dd class="col-sm-10">
                <a asp-area="" asp-controller="Books" asp-action="Details" asp-route-id="@Model.Book.Id">@Model.Book.Tittle</a>
            </dd>
        }
        @if (Model.Genre != null)
        {
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Genre)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Genre!.Name)
            </dd>
        }
        @if (Model.Author != null)
        {
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Author)
            </dt>
            <dd class="col-sm-10">
                <a asp-area="" asp-controller="Authors" asp-action="Details" asp-route-id="@Model.Author.Id">@Model.Author.Name</a>
            </dd>
        }
        <dt class="col-sm-2">Creator</dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AppUser!.UserName)
        </dd>
        <dt class="col-sm-2">Created</dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreationTime)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>

        <!-- Display associated topics -->
        <dt class="col-sm-2">
            Topics
        </dt>
        <dd class="col-sm-10">
            @if (ViewData["Topics"] != null && ((List<Topic>)ViewData["Topics"]!).Any())
            {
                @foreach (var topic in (ViewData["Topics"] as List<Topic>)!)
                {
                    <div>
                        <a asp-area="" asp-controller="Topics" asp-action="Details" asp-route-id="@topic.Id">
                            <strong>@Html.DisplayFor(model => topic.Tittle) -- @Html.DisplayFor(model => topic.AppUser!.UserName)</strong>
                            <div>@Html.DisplayFor(model => topic.Content) -- @Html.DisplayFor(model => topic.CreationTime)</div>
                        </a>
                        <!-- Add more properties of the Topic entity as needed -->
                    </div>

                    <!-- Display messages for each topic -->
                    @if (ViewData["Messages"] != null && ((List<App.Domain.Entities.Message>)ViewData["Messages"]!).Any())
                    {
                        <div>
                            <button class="toggleMessagesBtn">↓</button>
                            <div class="messagesContainer" style="display: none;">
                                @foreach (var message in (ViewData["Messages"] as List<App.Domain.Entities.Message>)!)
                                {
                                    if (message.TopicId == topic.Id)
                                    {
                                        <div>
                                            <span>@Html.DisplayFor(model => message.AppUser!.UserName) -- @Html.DisplayFor(model => message.Content)</span>
                                        </div>
                                    }
                                }
                            </div>

                        </div>
                    }
                }
            }
            else
            {
                <p>No topics found for this discussion.</p>
            }


            <!-- Button to show/hide create topic form -->
            <button id="btnCreateTopic">Create Topic</button>

            <!-- Create Topic Form (initially hidden) -->
            <div id="createTopicForm" style="display:none;">
                <h4>Create Topic</h4>
                <form asp-controller="Topics" asp-action="Create" method="post">
                    @* Select current user *@
                    <input type="hidden" name="AppUserId" value="@User.FindFirstValue(ClaimTypes.NameIdentifier)"/>
                    @* Select current discussion *@
                    <input type="hidden" name="DiscussionId" value="@Model.Id"/>
                    <div class="form-group">
                        <label class="control-label">Tittle</label>
                        <input class="form-control" name="Tittle"/>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Content</label>
                        <input class="form-control" name="Content"/>
                    </div>
                    <button type="submit">Create</button>
                </form>
            </div>

        </dd>

    </dl>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        var createTopicForm = document.getElementById('createTopicForm');
        var btnCreateTopic = document.getElementById('btnCreateTopic');
        
        var toggleButtons = document.querySelectorAll('.toggleMessagesBtn');

        btnCreateTopic.addEventListener('click', function () {
            createTopicForm.style.display = (createTopicForm.style.display === 'none') ? 'block' : 'none';
        });
        
        toggleButtons.forEach(function (button) {
             button.addEventListener('click', function () {
                var messagesContainer = button.nextElementSibling;
                messagesContainer.style.display = (messagesContainer.style.display === 'none') ? 'block' : 'none';
             });
        });
    });
</script>

BookHub/WebApp/Views/Discussions/Edit.cshtml
@using Microsoft.IdentityModel.Tokens
@model App.Domain.Entities.Discussion

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Discussion</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        @if (!Model.imageData.IsNullOrEmpty())
        {
            <img src="data:image;base64,@Convert.ToBase64String(Model.imageData)" width="180px" height="270px" alt="Picture not found!"/>
        }
            <div class="form-group">
                <label asp-for="BookId" class="control-label"></label>
                <select asp-for="BookId" class="form-control" asp-items="ViewBag.BookId">
                    <option></option>
                </select>
                <span asp-validation-for="BookId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GenreId" class="control-label"></label>
                <select asp-for="GenreId" class="form-control" asp-items="ViewBag.GenreId">
                    <option></option>
                </select>
                <span asp-validation-for="GenreId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuthorId" class="control-label"></label>
                <select asp-for="AuthorId" class="form-control" asp-items="ViewBag.AuthorId">
                    <option></option>
                </select>
                <span asp-validation-for="AuthorId" class="text-danger"></span>
            </div>
            <div class="form-group" style="display: none">
                <label asp-for="AppUserId" class="control-label"></label>
                <select asp-for="AppUserId" class="form-control" asp-items="ViewBag.AppUserId"></select>
                <span asp-validation-for="AppUserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tittle" class="control-label"></label>
                <input asp-for="Tittle" class="form-control" />
                <span asp-validation-for="Tittle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="imageData" class="control-label">Image</label>
                <input asp-for="imageData" class="form-control" type="file" value="@Model.imageData"/>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BookHub/WebApp/Views/Discussions/Index.cshtml
@using Microsoft.IdentityModel.Tokens
@model IEnumerable<App.Domain.Entities.Discussion>

@{
    ViewData["Title"] = "Index";
}

<h1>Discussions</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
    <tr>
        <th>Picture</th>
        <th></th>
        <th>
            @Html.DisplayNameFor(model => model.Tittle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AppUser)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Book)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Genre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Author)
        </th>
    </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
    <tr>
        <td>
        @if (!item.imageData.IsNullOrEmpty())
        {
            <img src="data:image;base64,@Convert.ToBase64String(item.imageData)" width="180px" height="270px" alt="Picture not found!"/>
        }
        </td>
        <td><a asp-action="Details" asp-route-id="@item.Id">Open</a></td>
        <td>
            @Html.DisplayFor(modelItem => item.Tittle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AppUser!.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @if (item.Book != null)
            {
                @Html.DisplayFor(modelItem => item.Book.Tittle)
            }
            else
            {<span>---</span>}
        </td>
        <td>
            @if (item.Genre != null)
            {
                @Html.DisplayFor(modelItem => item.Genre.Name)
            }
            else
            {<span>---</span>}
        </td>
        <td>
            @if (item.Author != null)
            {
                @Html.DisplayFor(modelItem => item.Author.Name)
            }
            else
            {<span>---</span>}
        </td>
    </tr>
}
    </tbody>
</table>