BookHub/WebApp/Controllers/PurchasedBooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using App.DAL.EF;
using App.Domain.Address_Tables;
using App.Domain.Identity;
using Microsoft.AspNetCore.Identity;
using System.Text.Json;
using App.Contracts.DAL;
using App.Domain.Entities;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class PurchasedBooksController : Controller
    {
        private readonly AppDbContext _context;
        private readonly UserManager<AppUser> _userManager;

        public PurchasedBooksController(AppDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> CreatePur()
        {
            var currentUser = await _userManager.GetUserAsync(User);

            if (currentUser == null)
            {
                return Unauthorized();
            }

            List<Guid> tempCart = GetTempCart();

            if (!tempCart.Any())
            {
                return RedirectToAction("Index");
            }

            var booksInTempCart = await _context.Books.Where(b => tempCart.Contains(b.Id)).ToListAsync();

            // Calculate the total cost and other properties of the purchase
            double totalValue = booksInTempCart.Sum(b => b.Price);
            double totalDiscount = 0; // Calculate discount

            // Create a new purchase
            var newPurchase = new Purchase
            {
                AppUserId = currentUser.Id,
                Value = totalValue,
                Discount = totalDiscount,
            };

            _context.Purchases.Add(newPurchase);
            await _context.SaveChangesAsync();

            // Create a PurchasedBook for each book in the purchase
            foreach (var book in booksInTempCart)
            {
                var purchasedBook = new PurchasedBook
                {
                    BookId = book.Id,
                    PurchaseId = newPurchase.Id,
                };

                _context.PurchasedBooks.Add(purchasedBook);
            }

            await _context.SaveChangesAsync();

            // Clear session after completing purchase
            HttpContext.Session.Remove("TempCart");

            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult RemoveFromTempCart(Guid id)
        {
            // Get current cart from session
            List<Guid> tempCart = GetTempCart();

            // Remove a book from the cart
            tempCart.Remove(id);

            // Save the updated cart in the session
            SetTempCart(tempCart);

            return RedirectToAction("Create"); // Redirect to the same place we were
        }
        
        public List<Guid> GetTempCart()
        {
            byte[]? cartData = HttpContext.Session.Get("TempCart");
            return (cartData != null
                ? JsonSerializer.Deserialize<List<Guid>>(cartData)
                : new List<Guid>())!;
        }
        
        private void SetTempCart(List<Guid> tempCart)
        {
            byte[] cartData = JsonSerializer.SerializeToUtf8Bytes(tempCart);
            HttpContext.Session.Set("TempCart", cartData);
        }
        
        // GET: PurchasedBooks
        public async Task<IActionResult> Index()
        {
            // var appDbContext = _context.PurchasedBooks.Include(p => p.Book).Include(p => p.Purchase);
            // return View(await appDbContext.ToListAsync());
            
            // Get current user
            var currentUser = await _userManager.GetUserAsync(User);

            if (currentUser == null)
            {
                return NotFound();
            }

            // Get all the user's purchased books
            var purchasedBooks = await _context.PurchasedBooks
                .Include(pb => pb.Book)
                .Include(pb => pb.Purchase)
                .Where(pb => pb.Purchase!.AppUserId == currentUser.Id)
                .ToListAsync();

            /*var reviews = await _uow.Ratings.GetAllAsync(currentUser.Id);*/
             var reviews = await _context.Ratings.Where(r => r.AppUserId == currentUser.Id).ToListAsync();
            
            ViewData["Reviews"] = reviews.ToList();
            return View(purchasedBooks);
        }

        // GET: PurchasedBooks/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var purchasedBook = await _context.PurchasedBooks
                .Include(p => p.Book)
                .Include(p => p.Purchase)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (purchasedBook == null)
            {
                return NotFound();
            }

            return View(purchasedBook);
        }

        // GET: PurchasedBooks/Create
        public async Task<IActionResult> Create()
        {
            var currentUser = await _userManager.GetUserAsync(User);

            if (currentUser == null)
            {
                return NotFound();
            }
            
            List<Guid> tempCart = GetTempCart();
            var viewModel = new CartModel()
            {
                Books = await _context.Books.Where(b => tempCart.Contains(b.Id)).ToListAsync(),
                IsBought = false
            };
            
            // ViewData["BookId"] = new SelectList(_context.Books, "Id", "Description");
            // ViewData["PurchaseId"] = new SelectList(_context.Purchases, "Id", "Id");
            return View(viewModel);
        }

        // POST: PurchasedBooks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        // [HttpPost]
        // [ValidateAntiForgeryToken]
        // public async Task<IActionResult> Create([Bind("BookId,PurchaseId,BookHasRead,Id")] PurchasedBook purchasedBook)
        // {
        //     if (ModelState.IsValid)
        //     {
        //         purchasedBook.Id = Guid.NewGuid();
        //         _context.Add(purchasedBook);
        //         await _context.SaveChangesAsync();
        //         return RedirectToAction(nameof(Index));
        //     }
        //     ViewData["BookId"] = new SelectList(_context.Books, "Id", "Description", purchasedBook.BookId);
        //     ViewData["PurchaseId"] = new SelectList(_context.Purchases, "Id", "Id", purchasedBook.PurchaseId);
        //     return View(purchasedBook);
        // }

        // GET: PurchasedBooks/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var purchasedBook = await _context.PurchasedBooks.FindAsync(id);
            if (purchasedBook == null)
            {
                return NotFound();
            }
            ViewData["BookId"] = new SelectList(_context.Books, "Id", "Description", purchasedBook.BookId);
            ViewData["PurchaseId"] = new SelectList(_context.Purchases, "Id", "Id", purchasedBook.PurchaseId);
            return View(purchasedBook);
        }

        // POST: PurchasedBooks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("BookId,PurchaseId,BookHasRead,Id")] PurchasedBook purchasedBook)
        {
            if (id != purchasedBook.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(purchasedBook);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PurchasedBookExists(purchasedBook.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BookId"] = new SelectList(_context.Books, "Id", "Description", purchasedBook.BookId);
            ViewData["PurchaseId"] = new SelectList(_context.Purchases, "Id", "Id", purchasedBook.PurchaseId);
            return View(purchasedBook);
        }

        // GET: PurchasedBooks/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var purchasedBook = await _context.PurchasedBooks
                .Include(p => p.Book)
                .Include(p => p.Purchase)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (purchasedBook == null)
            {
                return NotFound();
            }

            return View(purchasedBook);
        }

        // POST: PurchasedBooks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var purchasedBook = await _context.PurchasedBooks.FindAsync(id);
            if (purchasedBook != null)
            {
                _context.PurchasedBooks.Remove(purchasedBook);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PurchasedBookExists(Guid id)
        {

BookHub/WebApp/Controllers/RatingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using App.Contracts.BLL;
using App.Contracts.DAL;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using App.DAL.EF;
using App.Domain.Entities;

namespace WebApp.Controllers
{
    public class RatingsController : Controller
    {
        private readonly IAppBLL _bll;
        /*private readonly IAppUnitOfWork _uow;*/

        public RatingsController(IAppBLL bll)
        {
            _bll = bll;
            /*_uow = new AppUOW(context);*/
        }

        // GET: Ratings
        public async Task<IActionResult> Index()
        {
            var res = await _bll.Ratings.GetAllAsync();
            return View(res);
        }

        // GET: Ratings/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var rating = await _bll.Ratings.FirstOrDefaultAsync(id.Value);
            if (rating == null)
            {
                return NotFound();
            }

            return View(rating);
        }

        // GET: Ratings/Create
        public IActionResult Create()
        {
            ViewData["AppUserId"] = new SelectList(_bll.Users.GetAll(), "Id", "Id");
            return View();
        }

        // POST: Ratings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AppUserId,BookId,Value,Comment,Id")] App.BLL.DTO.Rating rating)
        {
            if (ModelState.IsValid)
            {
                rating.Id = Guid.NewGuid();
                _bll.Ratings.Add(rating);
                await _bll.SaveChangesAsync();
                return RedirectToAction("Index", "PurchasedBooks");
            }
            ViewData["AppUserId"] = new SelectList(_bll.Users.GetAll(), "Id", "Id", rating.AppUserId);
            return RedirectToAction("Index", "PurchasedBooks");
        }

        // GET: Ratings/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var rating = await _bll.Ratings.FirstOrDefaultIncludeAllAsync(id.Value);
            if (rating == null)
            {
                return NotFound();
            }
            ViewData["AppUserId"] = rating.AppUserId;
            ViewData["BookId"] = rating.BookId;
            /*ViewData["AppUserId"] = new SelectList(_bll.Users.GetAll(), "Id", "Id", rating.AppUserId);*/
            return View(rating);
        }

        // POST: Ratings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("AppUserId,BookId,Value,Comment,Id")] App.BLL.DTO.Rating rating)
        {
            if (id != rating.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _bll.Ratings.Update(rating);
                    await _bll.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (! await _bll.Ratings.ExistsAsync(rating.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "PurchasedBooks");
            }
            
            return RedirectToAction("Index", "PurchasedBooks");
        }

        // GET: Ratings/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rating = await _bll.Ratings
                .FirstOrDefaultAsync(id.Value);
            if (rating == null)
            {
                return NotFound();
            }

            return View(rating);
        }

        // POST: Ratings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var rating = await _bll.Ratings.ExistsAsync(id);
            if (rating)
            {
                await _bll.Ratings.RemoveAsync(id);
            }

            await _bll.SaveChangesAsync();
            return RedirectToAction("Index", "PurchasedBooks");
        }
    }
}

BookHub/WebApp/Views/PurchasedBooks/Create.cshtml
@model WebApp.Models.CartModel

@{
    ViewData["Title"] = "Shopping Cart";
    double totalValue = Model.Books.Sum(b => b.Price);
}

<h1>Shopping Cart</h1>

@if (Model.Books.Any())
{
    <table class="table">
        <thead>
        <tr>
            <th>Title</th>
            <th></th>
            <th>Price</th>
            <th>Remove from Cart</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var purchasedBook in Model.Books)
        {
            <tr>
                <td>
                    <img src="data:image;base64,@Convert.ToBase64String(@purchasedBook.imageData)" width="100px" height="130" alt=""/>
                </td>
                <td>@purchasedBook.Tittle</td>
                <td>@purchasedBook.Price$</td>
                <td>
                    <form asp-controller="PurchasedBooks" asp-action="RemoveFromTempCart" method="post">
                        <input type="hidden" name="id" value="@purchasedBook.Id"/>
                        <button type="submit">Remove</button>
                    </form>
                </td>
            </tr>
        }
        </tbody>
    </table>

    <form asp-controller="PurchasedBooks" asp-action="CreatePur" method="post">
        <button type="submit">Buy</button>
    </form>
    <span>Total: @totalValue$</span>
}
else
{
    <p>No items in the cart.</p>
}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BookHub/WebApp/Views/PurchasedBooks/Delete.cshtml
@model App.Domain.Address_Tables.PurchasedBook

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PurchasedBook</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Book)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Book!.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Purchase)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Purchase!.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookHasRead)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookHasRead)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BookHub/WebApp/Views/PurchasedBooks/Details.cshtml
@model App.Domain.Address_Tables.PurchasedBook

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>PurchasedBook</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Book)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Book!.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Purchase)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Purchase!.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookHasRead)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookHasRead)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

BookHub/WebApp/Views/PurchasedBooks/Edit.cshtml
@model App.Domain.Address_Tables.PurchasedBook

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>PurchasedBook</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BookId" class="control-label"></label>
                <select asp-for="BookId" class="form-control" asp-items="ViewBag.BookId"></select>
                <span asp-validation-for="BookId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PurchaseId" class="control-label"></label>
                <select asp-for="PurchaseId" class="form-control" asp-items="ViewBag.PurchaseId"></select>
                <span asp-validation-for="PurchaseId" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="BookHasRead" /> @Html.DisplayNameFor(model => model.BookHasRead)
                </label>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BookHub/WebApp/Views/PurchasedBooks/Index.cshtml
@using App.Domain.Entities
@using System.Security.Claims
@using System.Text
@model IEnumerable<App.Domain.Address_Tables.PurchasedBook>

@{
    ViewData["Title"] = "Index";
}

<h1>My Books</h1>

@if (Model.Any())
{
    <head>
        <style>
        .rating {
          display: flex;
          justify-content: center;
          align-items: center;
        }
        
        .rating input {
          display: none;
        }
        
        .rating label {
          cursor: pointer;
          font-size: 30px;
          color: #ccc;
        }
        
        .rating label:before {
          content: '\2605'; /* Unicode character for a star */
        }
        
        .rating input:checked ~ label {
          color: #f8d64e; /* Color for the selected stars */
        }
        
        /* Optional: Add hover effect */
        .rating input:not(:checked) ~ label:hover,
        .rating input:not(:checked):hover ~ label {
          color: #f8d64e;
        }
        </style>
    </head>
    <table class="table">
        <thead>
        <tr>
            <th>Book</th>
            <th>Title</th>
            <th>Price</th>
            <th>Book Has Read</th>
            <th>Your review</th>
        </tr>
        </thead>
        <tbody>
            @foreach (var purchasedBook in Model)
            {
                <tr>
                    <td>
                        <img src="data:image;base64,@Convert.ToBase64String(@purchasedBook.Book?.imageData)" width="100px" height="130" alt=""/>
                    </td>
                    <td>@purchasedBook.Book?.Tittle</td>
                    <td>@purchasedBook.Book?.Price</td>
                    <td>
                        <form asp-action="ToggleBookHasRead"><input type="hidden" name="id" value="@purchasedBook.Id">
                            <button type="submit">
                                @if (purchasedBook.BookHasRead)
                                {<span>&#10004;</span>}
                                else
                                {<span>X</span>}
                            </button></form>
                    </td>
                    <td>
                        @if (ViewData["Reviews"] is List<Rating> reviews && reviews.Any(review => review.BookId == purchasedBook.BookId))
                        {
                            var review = reviews.Single(review => review.BookId == purchasedBook.BookId);
                            <div style="font-size: x-large">@GenerateStarIcons(System.Convert.ToInt32(review.Value))</div>
                            <span>@review.Comment</span>
                            <div><a asp-area="" asp-controller="Ratings" asp-action="Edit" asp-route-id="@review.Id">--Edit--</a></div>
                            <span><a asp-area="" asp-controller="Ratings" asp-action="Delete" asp-route-id="@review.Id">--Delete Review--</a></span>
                        }
                        else
                        {
                            <button class="btnAddReview">Add Review</button>
                            <div class="addReviewForm" style="display:none;">
                                <form asp-controller="Ratings" asp-action="Create" method="post">
                                    @* Select current user *@
                                    <input type="hidden" name="AppUserId" value="@User.FindFirstValue(ClaimTypes.NameIdentifier)"/>
                                    @* Select current book *@
                                    <input type="hidden" name="BookId" value="@purchasedBook.BookId"/>
                                    <div class="rating">
                                        <input type="radio" id="star1_@purchasedBook.BookId" name="Value" value="5" />
                                        <label for="star1_@purchasedBook.BookId"></label>
                                        <input type="radio" id="star2_@purchasedBook.BookId" name="Value" value="4"/>
                                        <label for="star2_@purchasedBook.BookId"></label>
                                        <input type="radio" id="star3_@purchasedBook.BookId" name="Value" value="3"/>
                                        <label for="star3_@purchasedBook.BookId"></label>
                                        <input type="radio" id="star4_@purchasedBook.BookId" name="Value" value="2"/>
                                        <label for="star4_@purchasedBook.BookId"></label>
                                        <input type="radio" id="star5_@purchasedBook.BookId" name="Value" value="1"/>
                                        <label for="star5_@purchasedBook.BookId"></label>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label">Comment:</label>
                                        <input class="form-control" name="Comment"/>
                                    </div>
                                    <button type="submit">Add</button>
                                </form>
                            </div>
                        }
                    </td>
                    <td><form asp-action="Create" asp-controller="Ratings" method="post"></form></td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>No purchased books found.</p>
}

@functions {

    // Helper function to generate star icons based on the rating value
    string GenerateStarIcons(int rating)
    {
        StringBuilder stars = new StringBuilder();
        for (int i = 0; i < 5; i++)
        {
            if (i < rating)
            {
                stars.Append("★"); // Full star
            }
            else
            {
                stars.Append("☆"); // Empty star
            }
        }
        return stars.ToString();
    }

}

<script>
    document.addEventListener('DOMContentLoaded', function () {
        var toggleButtons = document.querySelectorAll('.btnAddReview');
        
        toggleButtons.forEach(function (button) {
             button.addEventListener('click', function () {
                var messagesContainer = button.nextElementSibling;
                messagesContainer.style.display = (messagesContainer.style.display === 'none') ? 'block' : 'none';
             });
        });
    });
</script>

@* <p> *@
@*     <a asp-action="Create">Create New</a> *@
@* </p> *@
@* <table class="table"> *@
@*     <thead> *@
@*         <tr> *@
@*             <th> *@
@*                 @Html.DisplayNameFor(model => model.Book) *@
@*             </th> *@
@*             <th> *@
@*                 @Html.DisplayNameFor(model => model.Purchase) *@
@*             </th> *@
@*             <th> *@
@*                 @Html.DisplayNameFor(model => model.BookHasRead) *@
@*             </th> *@
@*             <th></th> *@
@*         </tr> *@
@*     </thead> *@
@*     <tbody> *@
@* @foreach (var item in Model) { *@
@*         <tr> *@
@*             <td> *@
@*                 @Html.DisplayFor(modelItem => item.Book!.Description) *@
@*             </td> *@
@*             <td> *@
@*                 @Html.DisplayFor(modelItem => item.Purchase!.Id) *@
@*             </td> *@
@*             <td> *@
@*                 @Html.DisplayFor(modelItem => item.BookHasRead) *@
@*             </td> *@
@*             <td> *@
@*                 <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> | *@
@*                 <a asp-action="Details" asp-route-id="@item.Id">Details</a> | *@
@*                 <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> *@
@*             </td> *@
@*         </tr> *@
@* } *@
@*     </tbody> *@
@* </table> *@